-- CreateTable
CREATE TABLE "CallExecution" (
    "id" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "batchId" TEXT,
    "campaignId" TEXT,
    "status" TEXT NOT NULL,
    "smartStatus" TEXT,
    "provider" TEXT,
    "scheduledAt" TIMESTAMP(3),
    "initiatedAt" TIMESTAMP(3),
    "createdAtStr" TEXT,
    "updatedAtStr" TEXT,
    "answeredByVoicemail" BOOLEAN,
    "conversationDuration" DOUBLE PRECISION,
    "errorMessage" TEXT,
    "billingSettled" BOOLEAN,
    "processingStatus" TEXT,
    "userNumber" TEXT,
    "agentNumber" TEXT,
    "transcript" TEXT,
    "summary" TEXT,
    "totalCost" DOUBLE PRECISION,
    "llmCost" DOUBLE PRECISION,
    "networkCost" DOUBLE PRECISION,
    "platformCost" DOUBLE PRECISION,
    "synthesizerCost" DOUBLE PRECISION,
    "transcriberCost" DOUBLE PRECISION,
    "timeToFirstAudio" DOUBLE PRECISION,
    "streamId" DOUBLE PRECISION,
    "latencyRegion" TEXT,
    "recordingUrl" TEXT,
    "toNumber" TEXT,
    "fromNumber" TEXT,
    "callType" TEXT,
    "hangupBy" TEXT,
    "hangupReason" TEXT,
    "hangupProviderCode" INTEGER,
    "providerCallId" TEXT,
    "hostedTelephony" BOOLEAN,
    "retryCount" INTEGER,
    "usageBreakdown" TEXT,
    "costBreakdown" TEXT,
    "latencyData" TEXT,
    "extractedData" TEXT,
    "customExtractions" TEXT,
    "contextDetails" TEXT,
    "telephonyDataRaw" TEXT,
    "transferCallData" TEXT,
    "retryHistory" TEXT,
    "postProcessingPhases" TEXT,
    "batchRunDetails" TEXT,
    "agentContextDetails" TEXT,
    "agentExtraction" TEXT,
    "rawPayload" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CallExecution_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "CallExecution_status_idx" ON "CallExecution"("status");

-- CreateIndex
CREATE INDEX "CallExecution_agentId_idx" ON "CallExecution"("agentId");
